services:
  anon:
    build:
      context: .
      dockerfile_inline: |
        FROM debian:bookworm-slim
        RUN apt update && apt-get install -y ca-certificates wget
        RUN echo "anon anon/terms boolean true" | debconf-set-selections
        RUN . /etc/os-release && \
            wget -qO- https://deb.en.anyone.tech/anon.asc | tee /etc/apt/trusted.gpg.d/anon.asc && \
            echo "deb [signed-by=/etc/apt/trusted.gpg.d/anon.asc] https://deb.en.anyone.tech anon-live-bookworm main" | tee /etc/apt/sources.list.d/anon.list
        RUN apt-get update && apt-get install -y anon && apt-get clean && rm -rf /var/lib/apt/lists/*
        RUN mkdir -p /var/lib/anon/hidden_service && chown -R debian-anon:debian-anon /var/lib/anon/hidden_service/ && chmod 700 /var/lib/anon/hidden_service/
        RUN echo "HiddenServiceDir /var/lib/anon/hidden_service\nHiddenServicePort 80 nginx:80\nAgreeToTerms 1" > /etc/anon/anonrc
        USER debian-anon
        CMD anon -f /etc/anon/anonrc --agreetoterms 1
    volumes:
      - anon_data:/var/lib/anon/hidden_service
    restart: unless-stopped
    networks:
      - net

  nginx:
    depends_on: [anon]
    image: nginx:alpine
    volumes:
      - /var/run/tappd.sock:/var/run/tappd.sock
      - anon_data:/anon_data:ro
    command: sh -c "apk add --no-cache curl && /start.sh"
    configs:
      - source: nginx_script
        target: /start.sh
        mode: 0755
    restart: unless-stopped
    networks:
      - net

networks:
  net:

volumes:
  anon_data:

configs:
  nginx_script:
    content: |
      #!/bin/sh
      echo '<html><body><h1>Dstack TEE Anyone Anon Service</h1>' > /usr/share/nginx/html/index.html
      while [ ! -f /anon_data/hostname ]; do sleep 1; done
      addr=$$(cat /anon_data/hostname)
      echo "<p>$$addr</p>" >> /usr/share/nginx/html/index.html
      hash=$$(echo -n "$$addr" | sha256sum)
      payload="{\"report_data\":\"$$(echo -n $$hash | od -A n -t x1 | tr -d ' \n')\"}"
      attest=$$(curl -sX POST --unix-socket /var/run/tappd.sock -d "$$payload" http://localhost/prpc/Tappd.TdxQuote?json)
      echo "<pre style='white-space: pre-wrap;'>$$attest</pre></body></html>" >> /usr/share/nginx/html/index.html
      echo "Serving at $$addr"
      exec nginx -g 'daemon off;'
